// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batches.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createBatch = `-- name: CreateBatch :one
INSERT INTO batches(user_id, name, watermark_key, watermark_url) VALUES ($1, $2, $3, $4) RETURNING id, user_id, name, watermark_url, created_at, updated_at, deleted_at, watermark_key
`

type CreateBatchParams struct {
	UserID       uuid.UUID
	Name         sql.NullString
	WatermarkKey sql.NullString
	WatermarkUrl sql.NullString
}

func (q *Queries) CreateBatch(ctx context.Context, arg CreateBatchParams) (Batch, error) {
	row := q.db.QueryRowContext(ctx, createBatch,
		arg.UserID,
		arg.Name,
		arg.WatermarkKey,
		arg.WatermarkUrl,
	)
	var i Batch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.WatermarkUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.WatermarkKey,
	)
	return i, err
}
