// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images(batch_id, key, original_url) VALUES($1, $2, $3) RETURNING id, batch_id, key, original_url, processed_url, status, created_at, updated_at, deleted_at
`

type CreateImageParams struct {
	BatchID     uuid.UUID
	Key         string
	OriginalUrl string
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, createImage, arg.BatchID, arg.Key, arg.OriginalUrl)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.Key,
		&i.OriginalUrl,
		&i.ProcessedUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getImageByID = `-- name: GetImageByID :one
SELECT i.id, i.batch_id, i.key, i.original_url, i.processed_url, i.status, i.created_at, i.updated_at, i.deleted_at, b.watermark_url, b.watermark_text FROM images i INNER JOIN batches b ON b.id = i.batch_id WHERE i.id = $1 AND i.deleted_at IS NULL AND b.deleted_at IS NULL
`

type GetImageByIDRow struct {
	ID            uuid.UUID
	BatchID       uuid.UUID
	Key           string
	OriginalUrl   string
	ProcessedUrl  sql.NullString
	Status        ImageStatus
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
	WatermarkUrl  sql.NullString
	WatermarkText sql.NullString
}

func (q *Queries) GetImageByID(ctx context.Context, id uuid.UUID) (GetImageByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getImageByID, id)
	var i GetImageByIDRow
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.Key,
		&i.OriginalUrl,
		&i.ProcessedUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.WatermarkUrl,
		&i.WatermarkText,
	)
	return i, err
}

const updateImageByID = `-- name: UpdateImageByID :exec
UPDATE images SET processed_url = $1, status = $2, updated_at = NOW() WHERE id = $3 AND deleted_at IS NULL
`

type UpdateImageByIDParams struct {
	ProcessedUrl sql.NullString
	Status       ImageStatus
	ID           uuid.UUID
}

func (q *Queries) UpdateImageByID(ctx context.Context, arg UpdateImageByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateImageByID, arg.ProcessedUrl, arg.Status, arg.ID)
	return err
}
