// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ImageStatus string

const (
	ImageStatusPending    ImageStatus = "pending"
	ImageStatusProcessing ImageStatus = "processing"
	ImageStatusCompleted  ImageStatus = "completed"
	ImageStatusFailed     ImageStatus = "failed"
)

func (e *ImageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImageStatus(s)
	case string:
		*e = ImageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ImageStatus: %T", src)
	}
	return nil
}

type NullImageStatus struct {
	ImageStatus ImageStatus
	Valid       bool // Valid is true if ImageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ImageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImageStatus), nil
}

type Batch struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Name         sql.NullString
	WatermarkUrl sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
	WatermarkKey sql.NullString
}

type Image struct {
	ID           uuid.UUID
	BatchID      uuid.UUID
	Key          string
	OriginalUrl  string
	ProcessedUrl sql.NullString
	Status       ImageStatus
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	CreatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}
