// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images(batch_id, original_url) VALUES($1, $2) RETURNING id, batch_id, original_url, processed_url, status, created_at, updated_at, deleted_at
`

type CreateImageParams struct {
	BatchID     uuid.UUID
	OriginalUrl string
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, createImage, arg.BatchID, arg.OriginalUrl)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.OriginalUrl,
		&i.ProcessedUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
